version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_files:/usr/src/app/staticfiles
      - media_files:/usr/src/app/mediafiles
      - monitor_build:/usr/src/app/monitor
    depends_on:
      - backend
      # - monitor

  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=toplevel
      - POSTGRES_PASSWORD=toplevel
      - POSTGRES_DB=toplevel

  backend:
    build: ./backend
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py collectstatic --no-input --clear &&
                      gunicorn toplevel.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_files:/usr/src/app/staticfiles
      - media_files:/usr/src/app/mediafiles
    expose:
      - "8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=tu8&gqf87r#p8ilm95tayfzh7h39y)t!t2bori2+#r*@p_pl4&
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=toplevel
      - SQL_USER=toplevel
      - SQL_PASSWORD=toplevel
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  bot:
    build: ./bot
    command: bash -c "python start.py"
    depends_on:
      - backend

  monitor:
    build: ./monitor
    volumes:
      - monitor_build:/usr/src/app/build
    depends_on:
      - backend

volumes:
  postgres_data:
  static_files:
  media_files:
  monitor_build: